### Inventory file

#- The `ansible_host` variable should contain the `address/FQDN` used to gather facts and provision each node.
#- The `private_ip` variable should contain the `address/FQDN` used for the internal cluster communications.
#- Whether the environment is located in a local subnet, `ansible_host` and `private_ip` variables should match.
#- The ssh credentials used by Ansible during the provision can be specified in this file too. Another option is including them directly on the playbook.

## new format
all:
  hosts:
    tpc-waz-index01:
      ansible_host: 10.48.16.15
      private_ip: 10.48.16.15
      indexer_node_name: node-1
    tpc-waz-index02:
      ansible_host: 10.48.16.16
      private_ip: 10.48.16.16
      indexer_node_name: node-2
    tpc-waz-index03:
      ansible_host: 10.48.16.17
      private_ip: 10.48.16.17
      indexer_node_name: node-3
    tpc-waz-master01:
      ansible_host: 10.48.16.18
      private_ip: 10.48.16.18
      indexer_node_name: node-4
    tpc-waz-worker02:
      ansible_host: 10.48.16.19
      private_ip: 10.48.16.19
      indexer_node_name: node-5
    tpc-waz-dash01:
      ansible_host: 10.48.16.11
      private_ip: 10.48.16.11
      indexer_node_name: node-6
    tpchc-waz-worker03:
      ansible_host: 10.32.192.10
      private_ip: 10.32.192.10
      indexer_node_name: node-7
  children:
    wi_cluster:
      hosts:
        tpc-waz-index01:
        tpc-waz-index02:
        tpc-waz-index03:
    dashboard:
      hosts:
        tpc-waz-dash01:
    manager:
      hosts:
        tpc-waz-master01:
    workers:
      hosts:
        tpc-waz-worker02:
        tpchc-waz-worker03:


#```ini


# tpc-waz-index01 ansible_host=10.48.16.15 private_ip=10.48.16.15 indexer_node_name=node-1
# tpc-waz-index02 ansible_host=10.48.16.16 private_ip=10.48.16.16 indexer_node_name=node-2
# tpc-waz-index03 ansible_host=10.48.16.17 private_ip=10.48.16.17 indexer_node_name=node-3
# tpc-waz-dash01  ansible_host=10.48.16.11 private_ip=10.48.16.11 indexer_node_name=node-6
# tpc-waz-master01 ansible_host=10.48.16.18 private_ip=10.48.16.18 indexer_node_name=node-4
# tpc-waz-worker02  ansible_host=10.48.16.19 private_ip=10.48.16.19 indexer_node_name=node-5
# tpchc-waz-worker03 ansible_host=10.32.192.10 private_ip=10.32.192.10 indexer_node_name=node-7

# wi1 ansible_host=10.48.16.15 private_ip=10.48.16.15 #indexer_node_name=node-1
# wi2 ansible_host=10.48.16.16 private_ip=10.48.16.16 #indexer_node_name=node-2
# wi3 ansible_host=10.48.16.17 private_ip=10.48.16.17 #indexer_node_name=node-3
# #tpc-waz-dash01  ansible_host=10.48.16.11 private_ip=10.48.16.11 #indexer_node_name=node-6
# #tpc-waz-master01 ansible_host=10.48.16.18 private_ip=10.48.16.18 #indexer_node_name=node-4
# #tpc-waz-worker02  ansible_host=10.48.16.19 private_ip=10.48.16.19 #indexer_node_name=node-5
# #tpchc-waz-worker03 ansible_host=10.32.192.10 private_ip=10.32.192.10 #indexer_node_name=node-7

# wi1 ansible_host=10.48.16.15 private_ip=10.48.16.15 #indexer_node_name=node-1
# wi2 ansible_host=10.48.16.16 private_ip=10.48.16.16 #indexer_node_name=node-2
# wi3 ansible_host=10.48.16.17 private_ip=10.48.16.17 #indexer_node_name=node-3
# #tpc-waz-dash01  ansible_host=10.48.16.11 private_ip=10.48.16.11 #indexer_node_name=node-6
# #tpc-waz-master01 ansible_host=10.48.16.18 private_ip=10.48.16.18 #indexer_node_name=node-4
# #tpc-waz-worker02  ansible_host=10.48.16.19 private_ip=10.48.16.19 #indexer_node_name=node-5
# #tpchc-waz-worker03 ansible_host=10.32.192.10 private_ip=10.32.192.10 #indexer_node_name=node-7


# #indexer_admin_password=FQJNbk89txG#@^GIKMwLkF8twxnAW%81#eP6hGKXR$bKO@tLMI
# #dashboard_user=wazuh-admin
# #dashboard_password=FQJNbk89txG#@^GIKMwLkF8twxnAW%81#eP6hGKXR$bKO@tLMI

# # tpc-waz-index01:
# #   ansible_host: 10.48.16.15
# #   private_ip: 10.48.16.15
# #   indexer_node_name: node-1

# # tpc-waz-index02:
# #   ansible_host: 10.48.16.16
# #   private_ip: 10.48.16.16
# #   indexer_node_name: node-2

# # tpc-waz-index03:
# #   ansible_host: 10.48.16.17
# #   private_ip: 10.48.16.17
# #   indexer_node_name: node-3
 
# # tpc-waz-master01:
# #   ansible_host: 10.48.16.18
# #   private_ip: 10.48.16.18
# #   indexer_node_name: node-4

# # tpc-waz-worker02:
# #   ansible_host: 10.48.16.19
# #   private_ip: 10.48.16.19
# #   indexer_node_name: node-5

# # tpc-waz-dash01:
# #   ansible_host: 10.48.16.11
# #   private_ip: 10.48.16.11
# #   indexer_node_name: node-6

# # tpchc-waz-worker03:
# #   ansible_host: 10.32.192.10
# #   private_ip: 10.32.192.10
# #   indexer_node_name: node-7

# [node-1]
#   tpc-waz-index01
# [node-2]
#   tpc-waz-index02
# [node-3]
#   tpc-waz-index01
# [node-4]
#   tpc-waz-master01
# [node-5]
#   tpc-waz-worker02
# [node-6]
#   tpc-waz-dash01
# [node-7]
#   tpchc-waz-worker03

# [wi_cluster]
# tpc-waz-index01
# tpc-waz-index02
# tpc-waz-index03


# # [wi_cluster]
# # wi1
# # wi2
# # wi3
#   # [wi1]
#   #   tpc-waz-index01
#   # [wi2]
#   #   tpc-waz-index02
#   # [wi3] 
#   #   tpc-waz-index03

# [dashboard]
# tpc-waz-dash01

# [manager]
# tpc-waz-master01

# [worker02]
# tpc-waz-worker02

# [worker03]
# tpchc-waz-worker03


[all:vars]
ansible_ssh_user=root
ansible_ssh_private_key_file=/root/.ssh/id_rsa
ansible_ssh_extra_args='-o StrictHostKeyChecking=no'
indexer_admin_password=FQJNbk89txG#@^GIKMwLkF8twxnAW%81#eP6hGKXR$bKO@tLMI
dashboard_user=wazuh-admin
dashboard_password=FQJNbk89txG#@^GIKMwLkF8twxnAW%81#eP6hGKXR$bKO@tLMI
